/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class Vista_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Cliente
     */
    public Vista_Cliente() {
        initComponents();
    }

    public JButton getBtnAceptarCli() {
        return BtnAceptarCli;
    }

    public void setBtnAceptarCli(JButton BtnAceptarCli) {
        this.BtnAceptarCli = BtnAceptarCli;
    }

    public JButton getBtnActualizarCliente() {
        return BtnActualizarCliente;
    }

    public void setBtnActualizarCliente(JButton BtnActualizarCliente) {
        this.BtnActualizarCliente = BtnActualizarCliente;
    }

    public JButton getBtnBuscarPersona() {
        return BtnBuscarPersona;
    }

    public void setBtnBuscarPersona(JButton BtnBuscarPersona) {
        this.BtnBuscarPersona = BtnBuscarPersona;
    }

    public JButton getBtnCancelarCli() {
        return BtnCancelarCli;
    }

    public void setBtnCancelarCli(JButton BtnCancelarCli) {
        this.BtnCancelarCli = BtnCancelarCli;
    }

    public JButton getBtnCrearCliente() {
        return BtnCrearCliente;
    }

    public void setBtnCrearCliente(JButton BtnCrearCliente) {
        this.BtnCrearCliente = BtnCrearCliente;
    }

    public JButton getBtnEditarCliente() {
        return BtnEditarCliente;
    }

    public void setBtnEditarCliente(JButton BtnEditarCliente) {
        this.BtnEditarCliente = BtnEditarCliente;
    }

    public JButton getBtnImprimirCliente() {
        return BtnImprimirCliente;
    }

    public void setBtnImprimirCliente(JButton BtnImprimirCliente) {
        this.BtnImprimirCliente = BtnImprimirCliente;
    }

    public JButton getBtnRemoverCliente() {
        return BtnRemoverCliente;
    }

    public void setBtnRemoverCliente(JButton BtnRemoverCliente) {
        this.BtnRemoverCliente = BtnRemoverCliente;
    }

    public JDialog getDialogoCliente() {
        return DialogoCliente;
    }

    public void setDialogoCliente(JDialog DialogoCliente) {
        this.DialogoCliente = DialogoCliente;
    }

    public JTable getTblCliente() {
        return TblCliente;
    }

    public void setTblCliente(JTable TblCliente) {
        this.TblCliente = TblCliente;
    }

    public JTextField getTxtBuscarCliente() {
        return TxtBuscarCliente;
    }

    public void setTxtBuscarCliente(JTextField TxtBuscarCliente) {
        this.TxtBuscarCliente = TxtBuscarCliente;
    }

    public JTextField getTxtTelefonoCliente() {
        return TxtTelefonoCliente;
    }

    public void setTxtTelefonoCliente(JTextField TxtTelefonoCliente) {
        this.TxtTelefonoCliente = TxtTelefonoCliente;
    }

    public JTextField getTxt_ID_Cliente() {
        return Txt_ID_Cliente;
    }

    public void setTxt_ID_Cliente(JTextField Txt_ID_Cliente) {
        this.Txt_ID_Cliente = Txt_ID_Cliente;
    }

    public JTextField getTxt_ID_Persona() {
        return Txt_ID_Persona;
    }

    public void setTxt_ID_Persona(JTextField Txt_ID_Persona) {
        this.Txt_ID_Persona = Txt_ID_Persona;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoCliente = new javax.swing.JDialog();
        TxtTelefonoCliente = new javax.swing.JTextField();
        Txt_ID_Persona = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Txt_ID_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnBuscarPersona = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnAceptarCli = new javax.swing.JButton();
        BtnCancelarCli = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtBuscarCliente = new javax.swing.JTextField();
        BtnCrearCliente = new javax.swing.JButton();
        BtnEditarCliente = new javax.swing.JButton();
        BtnRemoverCliente = new javax.swing.JButton();
        BtnImprimirCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblEstado2 = new javax.swing.JLabel();
        BtnActualizarCliente = new javax.swing.JButton();

        jLabel10.setText("Id_Cliente:");

        jLabel3.setText("Id_Persiona:");

        jLabel2.setText("Telefono:");

        BtnBuscarPersona.setText("Buscar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        BtnAceptarCli.setText("Aceptar");

        BtnCancelarCli.setText("Cancelar");

        javax.swing.GroupLayout DialogoClienteLayout = new javax.swing.GroupLayout(DialogoCliente.getContentPane());
        DialogoCliente.getContentPane().setLayout(DialogoClienteLayout);
        DialogoClienteLayout.setHorizontalGroup(
            DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_ID_Persona)
                    .addComponent(Txt_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnBuscarPersona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAceptarCli)
                .addGap(26, 26, 26)
                .addComponent(BtnCancelarCli)
                .addGap(75, 75, 75))
        );
        DialogoClienteLayout.setVerticalGroup(
            DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoClienteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_ID_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptarCli)
                    .addComponent(BtnCancelarCli))
                .addGap(20, 20, 20))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Buscar");

        BtnCrearCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnCrearCliente.setText("Crear");

        BtnEditarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnEditarCliente.setText("Editar");

        BtnRemoverCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRemoverCliente.setText("Remover");

        BtnImprimirCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnImprimirCliente.setText("Imprimir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BtnCrearCliente)
                .addGap(33, 33, 33)
                .addComponent(BtnEditarCliente)
                .addGap(34, 34, 34)
                .addComponent(BtnRemoverCliente)
                .addGap(46, 46, 46)
                .addComponent(BtnImprimirCliente)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnImprimirCliente)
                    .addComponent(BtnRemoverCliente)
                    .addComponent(BtnEditarCliente)
                    .addComponent(BtnCrearCliente)
                    .addComponent(TxtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25))
        );

        TblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Telefono", "Id Persona"
            }
        ));
        jScrollPane1.setViewportView(TblCliente);

        jPanel4.setBackground(new java.awt.Color(220, 220, 220));

        lblEstado2.setText("Clientes 1.0");

        BtnActualizarCliente.setText("Actualizar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnActualizarCliente)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado2)
                    .addComponent(BtnActualizarCliente))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarCli;
    private javax.swing.JButton BtnActualizarCliente;
    private javax.swing.JButton BtnBuscarPersona;
    private javax.swing.JButton BtnCancelarCli;
    private javax.swing.JButton BtnCrearCliente;
    private javax.swing.JButton BtnEditarCliente;
    private javax.swing.JButton BtnImprimirCliente;
    private javax.swing.JButton BtnRemoverCliente;
    private javax.swing.JDialog DialogoCliente;
    private javax.swing.JTable TblCliente;
    private javax.swing.JTextField TxtBuscarCliente;
    private javax.swing.JTextField TxtTelefonoCliente;
    private javax.swing.JTextField Txt_ID_Cliente;
    private javax.swing.JTextField Txt_ID_Persona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado2;
    // End of variables declaration//GEN-END:variables
}
