/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Vista_Registro_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Registro_Usuario
     */
    public Vista_Registro_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_NombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Contrasenia = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txt_confirmarContra = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btn_cancelarRegistroUsuario = new javax.swing.JButton();
        btn_registrarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 70, -1, -1));

        txt_NombreUsuario.setToolTipText("Ingrese su Cedula");
        getContentPane().add(txt_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-añadir-grupo-de-usuarios-hombre-hombre-100.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setText("Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));
        getContentPane().add(txt_Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 170, 30));

        jLabel6.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));
        getContentPane().add(txt_confirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 170, 30));

        jLabel7.setFont(new java.awt.Font("Poiret One", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 40, 40));
        jLabel7.setText("Confirmar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        btn_cancelarRegistroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-cancelar-30.png"))); // NOI18N
        btn_cancelarRegistroUsuario.setText("Cancelar");
        getContentPane().add(btn_cancelarRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 119, -1));

        btn_registrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-añadir-usuario-masculino-30.png"))); // NOI18N
        btn_registrarUsuario.setText("Registrar");
        getContentPane().add(btn_registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 123, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Registrar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/F.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtn_cancelarRegistroUsuario() {
        return btn_cancelarRegistroUsuario;
    }

    public void setBtn_cancelarRegistroUsuario(JButton btn_cancelarRegistroUsuario) {
        this.btn_cancelarRegistroUsuario = btn_cancelarRegistroUsuario;
    }

    public JButton getBtn_registrarUsuario() {
        return btn_registrarUsuario;
    }

    public void setBtn_registrarUsuario(JButton btn_registrarUsuario) {
        this.btn_registrarUsuario = btn_registrarUsuario;
    }

    public JPasswordField getTxt_Contrasenia() {
        return txt_Contrasenia;
    }

    public void setTxt_Contrasenia(JPasswordField txt_Contrasenia) {
        this.txt_Contrasenia = txt_Contrasenia;
    }

    public JTextField getTxt_NombreUsuario() {
        return txt_NombreUsuario;
    }

    public void setTxt_NombreUsuario(JTextField txt_NombreUsuario) {
        this.txt_NombreUsuario = txt_NombreUsuario;
    }

    public JPasswordField getTxt_confirmarContra() {
        return txt_confirmarContra;
    }

    public void setTxt_confirmarContra(JPasswordField txt_confirmarContra) {
        this.txt_confirmarContra = txt_confirmarContra;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarRegistroUsuario;
    private javax.swing.JButton btn_registrarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txt_Contrasenia;
    private javax.swing.JTextField txt_NombreUsuario;
    private javax.swing.JPasswordField txt_confirmarContra;
    // End of variables declaration//GEN-END:variables
}
