/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class Vista_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Cliente
     */
    public Vista_Cliente() {
        initComponents();
    }

    public JButton getBtnAceptarCli() {
        return BtnAceptarCli;
    }

    public void setBtnAceptarCli(JButton BtnAceptarCli) {
        this.BtnAceptarCli = BtnAceptarCli;
    }

    public JButton getBtnActualizarCliente() {
        return BtnActualizarCliente;
    }

    public void setBtnActualizarCliente(JButton BtnActualizarCliente) {
        this.BtnActualizarCliente = BtnActualizarCliente;
    }

    public JButton getBtnCancelarCli() {
        return BtnCancelarCli;
    }

    public void setBtnCancelarCli(JButton BtnCancelarCli) {
        this.BtnCancelarCli = BtnCancelarCli;
    }

    public JButton getBtnCrearCliente() {
        return BtnCrearCliente;
    }

    public void setBtnCrearCliente(JButton BtnCrearCliente) {
        this.BtnCrearCliente = BtnCrearCliente;
    }

    public JButton getBtnEditarCliente() {
        return BtnEditarCliente;
    }

    public void setBtnEditarCliente(JButton BtnEditarCliente) {
        this.BtnEditarCliente = BtnEditarCliente;
    }


    public JButton getBtnRemoverCliente() {
        return BtnRemoverCliente;
    }

    public void setBtnRemoverCliente(JButton BtnRemoverCliente) {
        this.BtnRemoverCliente = BtnRemoverCliente;
    }

    public JDialog getDialogoCliente() {
        return DialogoCliente;
    }

    public void setDialogoCliente(JDialog DialogoCliente) {
        this.DialogoCliente = DialogoCliente;
    }

    public JTable getTblCliente() {
        return TblCliente;
    }

    public void setTblCliente(JTable TblCliente) {
        this.TblCliente = TblCliente;
    }

    public JTextField getTxtBuscarCliente() {
        return TxtBuscarCliente;
    }

    public void setTxtBuscarCliente(JTextField TxtBuscarCliente) {
        this.TxtBuscarCliente = TxtBuscarCliente;
    }

    public JTextField getTxtTelefonoCliente() {
        return TxtTelefonoCliente;
    }

    public void setTxtTelefonoCliente(JTextField TxtTelefonoCliente) {
        this.TxtTelefonoCliente = TxtTelefonoCliente;
    }

    public JTextField getTxt_ID_Cliente() {
        return Txt_ID_Cliente;
    }

    public void setTxt_ID_Cliente(JTextField Txt_ID_Cliente) {
        this.Txt_ID_Cliente = Txt_ID_Cliente;
    }

    public JTextField getTxt_ID_Persona() {
        return Txt_ID_Persona;
    }

    public void setTxt_ID_Persona(JTextField Txt_ID_Persona) {
        this.Txt_ID_Persona = Txt_ID_Persona;
    }

    public JLabel getLblNombresClienteBusqueda() {
        return LblNombresClienteBusqueda;
    }

    public void setLblNombresClienteBusqueda(JLabel LblNombresClienteBusqueda) {
        this.LblNombresClienteBusqueda = LblNombresClienteBusqueda;
    }

    public JTextField getTxtBuscarCedulaCli() {
        return TxtBuscarCedulaCli;
    }

    public void setTxtBuscarCedulaCli(JTextField TxtBuscarCedulaCli) {
        this.TxtBuscarCedulaCli = TxtBuscarCedulaCli;
    }

    public JPanel getJpanelInformacionBusqueda() {
        return JpanelInformacionBusqueda;
    }

    public void setJpanelInformacionBusqueda(JPanel JpanelInformacionBusqueda) {
        this.JpanelInformacionBusqueda = JpanelInformacionBusqueda;
    }

    public JSeparator getSeparatorCliente() {
        return SeparatorCliente;
    }

    public void setSeparatorCliente(JSeparator SeparatorCliente) {
        this.SeparatorCliente = SeparatorCliente;
    }

    public JLabel getLblNameBuscar() {
        return LblNameBuscar;
    }

    public void setLblNameBuscar(JLabel LblNameBuscar) {
        this.LblNameBuscar = LblNameBuscar;
    }

    public JLabel getLblFechaAcutualVC() {
        return LblFechaAcutualVC;
    }

    public void setLblFechaAcutualVC(JLabel LblFechaAcutualVC) {
        this.LblFechaAcutualVC = LblFechaAcutualVC;
    }

    public JSeparator getSeparatorMedioVC() {
        return SeparatorMedioVC;
    }

    public void setSeparatorMedioVC(JSeparator SeparatorMedioVC) {
        this.SeparatorMedioVC = SeparatorMedioVC;
    }

    public JSeparator getSeparatorResultVC() {
        return SeparatorResultVC;
    }

    public void setSeparatorResultVC(JSeparator SeparatorResultVC) {
        this.SeparatorResultVC = SeparatorResultVC;
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoCliente = new javax.swing.JDialog();
        TxtTelefonoCliente = new javax.swing.JTextField();
        Txt_ID_Persona = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Txt_ID_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnAceptarCli = new javax.swing.JButton();
        BtnCancelarCli = new javax.swing.JButton();
        JpanelInformacionBusqueda = new javax.swing.JPanel();
        TxtBuscarCedulaCli = new javax.swing.JTextField();
        LblNameBuscar = new javax.swing.JLabel();
        SeparatorCliente = new javax.swing.JSeparator();
        SeparatorMedioVC = new javax.swing.JSeparator();
        LblNombresClienteBusqueda = new javax.swing.JLabel();
        SeparatorResultVC = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblEstado2 = new javax.swing.JLabel();
        BtnCrearCliente = new javax.swing.JButton();
        BtnEditarCliente = new javax.swing.JButton();
        BtnRemoverCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnActualizarCliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtBuscarCliente = new javax.swing.JTextField();
        lblbuscar = new javax.swing.JLabel();
        LblFechaAcutualVC = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        jLabel10.setText("Id_Cliente:");

        jLabel3.setText("Id_Persiona:");

        jLabel2.setText("Telefono:");

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(191, 191, 191))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        BtnAceptarCli.setText("Aceptar");

        BtnCancelarCli.setText("Cancelar");

        JpanelInformacionBusqueda.setBackground(new java.awt.Color(255, 255, 255));

        TxtBuscarCedulaCli.setBorder(null);

        LblNameBuscar.setText("Buscar:");

        SeparatorCliente.setBackground(new java.awt.Color(0, 0, 102));

        SeparatorMedioVC.setBackground(new java.awt.Color(51, 0, 255));
        SeparatorMedioVC.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SeparatorResultVC.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout JpanelInformacionBusquedaLayout = new javax.swing.GroupLayout(JpanelInformacionBusqueda);
        JpanelInformacionBusqueda.setLayout(JpanelInformacionBusquedaLayout);
        JpanelInformacionBusquedaLayout.setHorizontalGroup(
            JpanelInformacionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelInformacionBusquedaLayout.createSequentialGroup()
                .addGroup(JpanelInformacionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelInformacionBusquedaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(SeparatorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelInformacionBusquedaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblNameBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBuscarCedulaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(SeparatorMedioVC, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelInformacionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNombresClienteBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SeparatorResultVC))
                .addContainerGap())
        );
        JpanelInformacionBusquedaLayout.setVerticalGroup(
            JpanelInformacionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelInformacionBusquedaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblNombresClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelInformacionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparatorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeparatorResultVC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(JpanelInformacionBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpanelInformacionBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNameBuscar)
                    .addComponent(TxtBuscarCedulaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addComponent(SeparatorMedioVC)
        );

        javax.swing.GroupLayout DialogoClienteLayout = new javax.swing.GroupLayout(DialogoCliente.getContentPane());
        DialogoCliente.getContentPane().setLayout(DialogoClienteLayout);
        DialogoClienteLayout.setHorizontalGroup(
            DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DialogoClienteLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_ID_Persona)
                    .addComponent(Txt_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(DialogoClienteLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(BtnAceptarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelarCli)
                .addGap(92, 92, 92))
            .addComponent(JpanelInformacionBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoClienteLayout.setVerticalGroup(
            DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoClienteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelInformacionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_ID_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DialogoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptarCli)
                    .addComponent(BtnCancelarCli))
                .addGap(26, 26, 26))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Apellido", "Nombre", "Telefono", "Id Persona"
            }
        ));
        jScrollPane1.setViewportView(TblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 770, 310));

        jPanel4.setBackground(new java.awt.Color(220, 220, 220));

        lblEstado2.setText("Clientes 1.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado2)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1040, 30));

        BtnCrearCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnCrearCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-grupo-de-usuarios-hombre-y-mujer-48.png"))); // NOI18N
        BtnCrearCliente.setText("Crear");
        BtnCrearCliente.setBorder(null);
        BtnCrearCliente.setContentAreaFilled(false);
        getContentPane().add(BtnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, -1));

        BtnEditarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-grupo-de-usuarios-hombre-y-mujer-48 (2).png"))); // NOI18N
        BtnEditarCliente.setText("Editar");
        BtnEditarCliente.setBorder(null);
        BtnEditarCliente.setContentAreaFilled(false);
        getContentPane().add(BtnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, -1));

        BtnRemoverCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRemoverCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-grupo-de-usuarios-hombre-y-mujer-48 (1).png"))); // NOI18N
        BtnRemoverCliente.setText("Remover");
        BtnRemoverCliente.setBorder(null);
        BtnRemoverCliente.setContentAreaFilled(false);
        getContentPane().add(BtnRemoverCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 140, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/tabla_eje1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 280));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/Servicios_Logo_150.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 150, 160));

        BtnActualizarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-actualizar-48.png"))); // NOI18N
        BtnActualizarCliente.setText("Actualizar");
        BtnActualizarCliente.setBorder(null);
        BtnActualizarCliente.setContentAreaFilled(false);
        getContentPane().add(BtnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("REGISTRO CLIENTE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 320, 40));
        getContentPane().add(TxtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 370, 20));

        lblbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-busca-mas-48.png"))); // NOI18N
        getContentPane().add(lblbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 40));
        getContentPane().add(LblFechaAcutualVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 120, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 320, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/Blancoceleste.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarCli;
    private javax.swing.JButton BtnActualizarCliente;
    private javax.swing.JButton BtnCancelarCli;
    private javax.swing.JButton BtnCrearCliente;
    private javax.swing.JButton BtnEditarCliente;
    private javax.swing.JButton BtnRemoverCliente;
    private javax.swing.JDialog DialogoCliente;
    private javax.swing.JPanel JpanelInformacionBusqueda;
    private javax.swing.JLabel LblFechaAcutualVC;
    private javax.swing.JLabel LblNameBuscar;
    private javax.swing.JLabel LblNombresClienteBusqueda;
    private javax.swing.JSeparator SeparatorCliente;
    private javax.swing.JSeparator SeparatorMedioVC;
    private javax.swing.JSeparator SeparatorResultVC;
    private javax.swing.JTable TblCliente;
    private javax.swing.JTextField TxtBuscarCedulaCli;
    private javax.swing.JTextField TxtBuscarCliente;
    private javax.swing.JTextField TxtTelefonoCliente;
    private javax.swing.JTextField Txt_ID_Cliente;
    private javax.swing.JTextField Txt_ID_Persona;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblbuscar;
    // End of variables declaration//GEN-END:variables
}
